/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package two_to_one;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class twoToOneTest {
    @Test public void combinesTwoStringsAlreadyInOrder() {
        twoToOne classUnderTest = new twoToOne();
        assertEquals("combines two strings already in alphabetical order", String.valueOf("abcdef"), classUnderTest.rearrangeStrings("abc", "def"));
    }

    @Test public void combinesTwoStringsNotInOrder() {
        twoToOne classUnderTest = new twoToOne();
        assertEquals("combines two strings not in alphabetical order", String.valueOf("abcdef"), classUnderTest.rearrangeStrings("def", "abc"));
    }

    @Test public void combinesTwoStringsWithDuplicates() {
        twoToOne classUnderTest = new twoToOne();
        assertEquals("removes all duplicates", String.valueOf("abcdef"), classUnderTest.rearrangeStrings("aabbcc", "ddeeff"));
    }

    @Test public void removesCharactersThatAreNotLetters() {
        twoToOne classUnderTest = new twoToOne();
        assertEquals("removes non alphabetical characters", String.valueOf("abcdef"), classUnderTest.rearrangeStrings("abc!", "def?"));
    }
}
