/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package digital_root;

public class DigitalRoot {
    public Integer digital_root(Integer number) {
        while (number > 9) {
            Integer addition = 0;
            String numberString = Integer.toString(number);
            String[] stringArray = numberString.split("");
            for (Integer element = 0; element < stringArray.length; element++) {
                Integer digit = Integer.parseInt(stringArray[element]);
                addition += digit;
            }
            number = addition;
        }
        return number;
    }
}
