/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.stop_gninnips_my_sdrow;

public class Spinning {
    public String spinTheWords(String wordsString) {
        String[] wordsArray = wordsString.split(" ");
        for (Integer integer = 0; integer < wordsArray.length; integer++) {
            if (wordsArray[integer].length() >= 5) {
                wordsArray[integer] = new StringBuffer(wordsArray[integer]).reverse().toString();
            }
        }
        String reversedString = String.join(" ", wordsArray);
        return reversedString;
    }
}
